import type { StoryDialogNode } from '@/game/story/types.ts'

export const STORY_DIALOG_NODES: StoryDialogNode[] = [
  {
    id: 'thorne_intro',
    npcId: 'thorne',
    textKey: 'story_node_thorne_intro',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'roadside_whispers', status: 'inactive' }],
    options: [
      {
        id: 'thorne_offer_whispers',
        textKey: 'story_option_thorne_offer_whispers',
        effects: [
          { type: 'set_story_flag', flag: 'heard_ashenford_whispers' },
          { type: 'adjust_relationship', npcId: 'thorne', amount: 4 },
          { type: 'start_story_quest', questId: 'roadside_whispers' },
        ],
        nextNodeId: 'thorne_offer_done',
      },
      {
        id: 'thorne_decline',
        textKey: 'story_option_thorne_decline',
        effects: [{ type: 'adjust_relationship', npcId: 'thorne', amount: -2 }],
        closes: true,
      },
    ],
  },
  {
    id: 'thorne_offer_done',
    npcId: 'thorne',
    textKey: 'story_node_thorne_offer_done',
    options: [{ id: 'thorne_done_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'thorne_progress',
    npcId: 'thorne',
    textKey: 'story_node_thorne_progress',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'roadside_whispers', status: 'active' }],
    options: [{ id: 'thorne_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'thorne_after',
    npcId: 'thorne',
    textKey: 'story_node_thorne_after',
    isRoot: true,
    priority: 6,
    conditions: [{ type: 'story_quest_status', questId: 'roadside_whispers', status: 'completed' }],
    options: [
      {
        id: 'thorne_after_brennan',
        textKey: 'story_option_thorne_after_brennan',
        effects: [{ type: 'set_story_flag', flag: 'stoneholt_tip' }],
        nextNodeId: 'thorne_after_brennan_reply',
      },
      { id: 'thorne_after_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'thorne_after_brennan_reply',
    npcId: 'thorne',
    textKey: 'story_node_thorne_after_brennan_reply',
    options: [{ id: 'thorne_after_brennan_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'veris_intro',
    npcId: 'veris',
    textKey: 'story_node_veris_intro',
    isRoot: true,
    priority: 12,
    conditions: [
      { type: 'story_flag', flag: 'veris_contact' },
      { type: 'story_quest_status', questId: 'crossroads_manifest', status: 'inactive' },
    ],
    options: [
      {
        id: 'veris_offer_manifest',
        textKey: 'story_option_veris_offer_manifest',
        effects: [
          { type: 'set_story_flag', flag: 'knows_crown_pressure' },
          { type: 'adjust_relationship', npcId: 'veris', amount: 5 },
          { type: 'start_story_quest', questId: 'crossroads_manifest' },
        ],
        nextNodeId: 'veris_offer_done',
      },
      {
        id: 'veris_bribe',
        textKey: 'story_option_veris_bribe',
        conditions: [{ type: 'gold_at_least', amount: 20 }],
        effects: [
          { type: 'pay_gold', amount: 20 },
          { type: 'adjust_relationship', npcId: 'veris', amount: 8 },
          { type: 'unlock_easter_egg', easterEggId: 'veris_loves_exact_change' },
        ],
        nextNodeId: 'veris_bribe_reply',
      },
      { id: 'veris_intro_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'veris_offer_done',
    npcId: 'veris',
    textKey: 'story_node_veris_offer_done',
    options: [{ id: 'veris_offer_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'veris_bribe_reply',
    npcId: 'veris',
    textKey: 'story_node_veris_bribe_reply',
    options: [{ id: 'veris_bribe_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'veris_progress',
    npcId: 'veris',
    textKey: 'story_node_veris_progress',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'crossroads_manifest', status: 'active' }],
    options: [{ id: 'veris_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'veris_double_intro',
    npcId: 'veris',
    textKey: 'story_node_veris_double_intro',
    isRoot: true,
    priority: 9,
    conditions: [{ type: 'story_quest_status', questId: 'double_booked', status: 'inactive' }],
    options: [
      {
        id: 'veris_start_double',
        textKey: 'story_option_veris_start_double',
        conditions: [
          {
            type: 'all_of',
            conditions: [
              { type: 'story_quest_status', questId: 'crown_license', status: 'completed' },
              { type: 'story_quest_status', questId: 'quiet_relay', status: 'completed' },
            ],
          },
        ],
        effects: [{ type: 'start_story_quest', questId: 'double_booked' }],
        nextNodeId: 'veris_double_started',
      },
      {
        id: 'veris_reveal_seal',
        textKey: 'story_option_veris_reveal_seal',
        conditions: [{ type: 'story_flag', flag: 'double_agent' }],
        effects: [{ type: 'unlock_easter_egg', easterEggId: 'veris_wore_the_seal' }],
        nextNodeId: 'veris_reveal_seal_reply',
      },
      { id: 'veris_double_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'veris_double_started',
    npcId: 'veris',
    textKey: 'story_node_veris_double_started',
    options: [{ id: 'veris_double_started_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'veris_reveal_seal_reply',
    npcId: 'veris',
    textKey: 'story_node_veris_reveal_seal_reply',
    options: [{ id: 'veris_reveal_seal_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'veris_double_progress',
    npcId: 'veris',
    textKey: 'story_node_veris_double_progress',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'double_booked', status: 'active' }],
    options: [{ id: 'veris_double_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'aldric_intro',
    npcId: 'aldric',
    textKey: 'story_node_aldric_intro',
    isRoot: true,
    priority: 12,
    conditions: [{ type: 'story_quest_status', questId: 'crown_license', status: 'inactive' }],
    options: [
      {
        id: 'aldric_accept',
        textKey: 'story_option_aldric_accept',
        conditions: [{ type: 'gold_at_least', amount: 80 }],
        effects: [
          { type: 'pay_gold', amount: 80 },
          { type: 'set_story_flag', flag: 'crown_registered' },
          { type: 'adjust_relationship', npcId: 'aldric', amount: 8 },
          { type: 'start_story_quest', questId: 'crown_license' },
        ],
        nextNodeId: 'aldric_accept_done',
      },
      {
        id: 'aldric_probe',
        textKey: 'story_option_aldric_probe',
        effects: [{ type: 'set_story_flag', flag: 'aldric_heard_questions' }],
        nextNodeId: 'aldric_probe_reply',
      },
      { id: 'aldric_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'aldric_accept_done',
    npcId: 'aldric',
    textKey: 'story_node_aldric_accept_done',
    options: [{ id: 'aldric_accept_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'aldric_probe_reply',
    npcId: 'aldric',
    textKey: 'story_node_aldric_probe_reply',
    options: [{ id: 'aldric_probe_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'aldric_progress',
    npcId: 'aldric',
    textKey: 'story_node_aldric_progress',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'crown_license', status: 'active' }],
    options: [{ id: 'aldric_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'aldric_after',
    npcId: 'aldric',
    textKey: 'story_node_aldric_after',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'crown_license', status: 'completed' }],
    options: [{ id: 'aldric_after_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'lyris_intro',
    npcId: 'lyris',
    textKey: 'story_node_lyris_intro',
    isRoot: true,
    priority: 12,
    conditions: [{ type: 'story_quest_status', questId: 'quiet_relay', status: 'inactive' }],
    options: [
      {
        id: 'lyris_accept',
        textKey: 'story_option_lyris_accept',
        effects: [
          { type: 'set_story_flag', flag: 'heard_free_traders' },
          { type: 'adjust_relationship', npcId: 'lyris', amount: 8 },
          { type: 'start_story_quest', questId: 'quiet_relay' },
        ],
        nextNodeId: 'lyris_accept_done',
      },
      {
        id: 'lyris_ask_price',
        textKey: 'story_option_lyris_ask_price',
        effects: [{ type: 'set_story_flag', flag: 'lyris_named_the_price' }],
        nextNodeId: 'lyris_ask_price_reply',
      },
      { id: 'lyris_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'lyris_accept_done',
    npcId: 'lyris',
    textKey: 'story_node_lyris_accept_done',
    options: [{ id: 'lyris_accept_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'lyris_ask_price_reply',
    npcId: 'lyris',
    textKey: 'story_node_lyris_ask_price_reply',
    options: [{ id: 'lyris_ask_price_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'lyris_progress',
    npcId: 'lyris',
    textKey: 'story_node_lyris_progress',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'quiet_relay', status: 'active' }],
    options: [{ id: 'lyris_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'lyris_after',
    npcId: 'lyris',
    textKey: 'story_node_lyris_after',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'quiet_relay', status: 'completed' }],
    options: [{ id: 'lyris_after_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'kess_intro',
    npcId: 'kess',
    textKey: 'story_node_kess_intro',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'harbor_tally', status: 'inactive' }],
    options: [
      {
        id: 'kess_start_tally',
        textKey: 'story_option_kess_start_tally',
        conditions: [{ type: 'story_quest_status', questId: 'crown_license', status: 'completed' }],
        effects: [
          { type: 'adjust_relationship', npcId: 'kess', amount: 5 },
          { type: 'start_story_quest', questId: 'harbor_tally' },
        ],
        nextNodeId: 'kess_start_tally_done',
      },
      { id: 'kess_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'kess_start_tally_done',
    npcId: 'kess',
    textKey: 'story_node_kess_start_tally_done',
    options: [{ id: 'kess_start_tally_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'kess_progress',
    npcId: 'kess',
    textKey: 'story_node_kess_progress',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'harbor_tally', status: 'active' }],
    options: [{ id: 'kess_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'kess_after',
    npcId: 'kess',
    textKey: 'story_node_kess_after',
    isRoot: true,
    priority: 6,
    conditions: [{ type: 'story_quest_status', questId: 'harbor_tally', status: 'completed' }],
    options: [{ id: 'kess_after_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'caera_intro',
    npcId: 'caera',
    textKey: 'story_node_caera_intro',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'fen_relay', status: 'inactive' }],
    options: [
      {
        id: 'caera_start_relay',
        textKey: 'story_option_caera_start_relay',
        conditions: [{ type: 'story_quest_status', questId: 'quiet_relay', status: 'completed' }],
        effects: [
          { type: 'adjust_relationship', npcId: 'caera', amount: 6 },
          { type: 'start_story_quest', questId: 'fen_relay' },
        ],
        nextNodeId: 'caera_start_relay_done',
      },
      {
        id: 'caera_moss_secret',
        textKey: 'story_option_caera_moss_secret',
        effects: [{ type: 'unlock_easter_egg', easterEggId: 'caera_counts_boats_by_lanterns' }],
        nextNodeId: 'caera_moss_secret_reply',
      },
      { id: 'caera_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'caera_start_relay_done',
    npcId: 'caera',
    textKey: 'story_node_caera_start_relay_done',
    options: [{ id: 'caera_start_relay_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'caera_moss_secret_reply',
    npcId: 'caera',
    textKey: 'story_node_caera_moss_secret_reply',
    options: [{ id: 'caera_secret_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'caera_progress',
    npcId: 'caera',
    textKey: 'story_node_caera_progress',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'fen_relay', status: 'active' }],
    options: [{ id: 'caera_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'caera_after',
    npcId: 'caera',
    textKey: 'story_node_caera_after',
    isRoot: true,
    priority: 6,
    conditions: [{ type: 'story_quest_status', questId: 'fen_relay', status: 'completed' }],
    options: [{ id: 'caera_after_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'brennan_intro',
    npcId: 'brennan',
    textKey: 'story_node_brennan_intro',
    isRoot: true,
    priority: 10,
    conditions: [{ type: 'story_quest_status', questId: 'miners_union', status: 'inactive' }],
    options: [
      {
        id: 'brennan_start_union',
        textKey: 'story_option_brennan_start_union',
        effects: [
          { type: 'adjust_relationship', npcId: 'brennan', amount: 5 },
          { type: 'start_story_quest', questId: 'miners_union' },
        ],
        nextNodeId: 'brennan_start_union_done',
      },
      { id: 'brennan_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'brennan_start_union_done',
    npcId: 'brennan',
    textKey: 'story_node_brennan_start_union_done',
    options: [{ id: 'brennan_start_union_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'brennan_progress',
    npcId: 'brennan',
    textKey: 'story_node_brennan_progress',
    isRoot: true,
    priority: 8,
    conditions: [{ type: 'story_quest_status', questId: 'miners_union', status: 'active' }],
    options: [{ id: 'brennan_progress_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'brennan_after',
    npcId: 'brennan',
    textKey: 'story_node_brennan_after',
    isRoot: true,
    priority: 6,
    conditions: [{ type: 'story_quest_status', questId: 'miners_union', status: 'completed' }],
    options: [{ id: 'brennan_after_close', textKey: 'story_option_goodbye', closes: true }],
  },

  {
    id: 'halas_intro',
    npcId: 'halas',
    textKey: 'story_node_halas_intro',
    isRoot: true,
    priority: 10,
    options: [
      {
        id: 'halas_talk_route',
        textKey: 'story_option_halas_talk_route',
        nextNodeId: 'halas_route_reply',
      },
      {
        id: 'halas_double_agent',
        textKey: 'story_option_halas_double_agent',
        conditions: [{ type: 'story_quest_status', questId: 'double_booked', status: 'active' }],
        nextNodeId: 'halas_double_agent_reply',
      },
      {
        id: 'halas_free_keel',
        textKey: 'story_option_halas_free_keel',
        conditions: [{ type: 'story_flag', flag: 'reed_route_open' }],
        effects: [{ type: 'unlock_easter_egg', easterEggId: 'halas_named_his_ship_after_a_tax_collector' }],
        nextNodeId: 'halas_free_keel_reply',
      },
      { id: 'halas_close', textKey: 'story_option_goodbye', closes: true },
    ],
  },
  {
    id: 'halas_route_reply',
    npcId: 'halas',
    textKey: 'story_node_halas_route_reply',
    options: [{ id: 'halas_route_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'halas_double_agent_reply',
    npcId: 'halas',
    textKey: 'story_node_halas_double_agent_reply',
    options: [{ id: 'halas_double_close', textKey: 'story_option_goodbye', closes: true }],
  },
  {
    id: 'halas_free_keel_reply',
    npcId: 'halas',
    textKey: 'story_node_halas_free_keel_reply',
    options: [{ id: 'halas_free_keel_close', textKey: 'story_option_goodbye', closes: true }],
  },
]
