import type { StoryNpcDef } from '@/game/story/types.ts'

export const STORY_NPCS: StoryNpcDef[] = [
  {
    id: 'thorne',
    portraitId: 'thorne',
    townId: 'ashenford',
    name: 'Master Thorne',
    title: 'Ashenford Smith',
    shortDescriptionKey: 'story_npc_thorne_summary',
  },
  {
    id: 'veris',
    portraitId: 'veris',
    townId: 'mirecross',
    name: 'Veris Tollward',
    title: 'Crossroads Keeper',
    shortDescriptionKey: 'story_npc_veris_summary',
  },
  {
    id: 'kess',
    portraitId: 'kess',
    townId: 'riversend',
    name: 'Harbormaster Kess',
    title: 'Dockmaster of Riversend',
    shortDescriptionKey: 'story_npc_kess_summary',
  },
  {
    id: 'aldric',
    portraitId: 'aldric',
    townId: 'crownpost',
    name: 'Magistrate Aldric',
    title: 'Crown Exchange Warden',
    shortDescriptionKey: 'story_npc_aldric_summary',
  },
  {
    id: 'lyris',
    portraitId: 'lyris',
    townId: 'crownpost',
    name: 'Lyris Vale',
    title: 'Independent Factor',
    shortDescriptionKey: 'story_npc_lyris_summary',
  },
  {
    id: 'caera',
    portraitId: 'caera',
    townId: 'fenward',
    name: 'Caera of the Reeds',
    title: 'Fen Broker',
    shortDescriptionKey: 'story_npc_caera_summary',
  },
  {
    id: 'brennan',
    portraitId: 'brennan',
    townId: 'stoneholt',
    name: 'Factor Brennan',
    title: 'Mine Quartermaster',
    shortDescriptionKey: 'story_npc_brennan_summary',
  },
  {
    id: 'halas',
    portraitId: 'halas',
    townId: 'saltmere',
    name: 'Captain Halas',
    title: 'Saltmere Free Keel',
    shortDescriptionKey: 'story_npc_halas_summary',
  },
]
